"""Canonical BAMBO permission and system-role definitions."""

PERMISSIONS = (
    ("users.read", "Users", "مشاهده کاربران", False),
    ("users.manage", "Users", "ایجاد و مدیریت کاربران", True),
    ("roles.read", "Roles", "مشاهده نقش‌ها و دسترسی‌ها", False),
    ("roles.manage", "Roles", "ایجاد نقش و تغییر Permission", True),
    ("pilots.read", "Pilots", "مشاهده پرونده‌های پایلوت", False),
    ("pilots.create", "Pilots", "ایجاد پرونده پایلوت", False),
    ("pilots.manage", "Pilots", "ویرایش و مدیریت پرونده پایلوت", True),
    ("stage1.manage", "Stage 1", "مدیریت مرحله اول", False),
    ("forms.manage", "Forms", "ثبت و ویرایش F01 تا F05", False),
    ("forms.read", "Forms", "مشاهده فرم‌های رسمی پروژه", False),
    ("forms.print", "Forms", "چاپ فرم‌های رسمی پروژه", False),
    ("forms.export_pdf", "Forms", "خروجی PDF فرم‌های رسمی پروژه", False),
    ("forms.f01.read", "Forms", "مشاهده فرم رسمی F01", False),
    ("forms.f02.read", "Forms", "مشاهده فرم رسمی F02", False),
    ("forms.f03.read", "Forms", "مشاهده فرم رسمی F03", False),
    ("forms.f04.read", "Forms", "مشاهده فرم رسمی F04", False),
    ("forms.f05.read", "Forms", "مشاهده فرم رسمی F05", False),
    ("dwg.manage", "DWG", "ثبت و نسخه‌بندی DWG", True),
    ("missions.manage", "Missions", "مدیریت مأموریت‌ها", False),
    (
        "external_status.manage",
        "External Platform",
        "ثبت وضعیت Read-only پلتفرم اصلی",
        False,
    ),
    ("notifications.manage", "Notifications", "ثبت و پیگیری اعلان‌های عملیاتی", False),
    ("preferences.manage", "Preferences", "مدیریت تنظیمات کاربر", False),
    ("checklists.manage", "Checklists", "ثبت چک‌لیست و ارسال مرحله", False),
    ("gate_approval.approve", "Gate Approval", "تأیید Gate و مرحله", True),
    ("gate_approval.reject", "Gate Approval", "رد Gate و مرحله", True),
    ("incidents.manage", "Incidents", "ثبت و مدیریت رخدادها", False),
    ("customer_success.manage", "Customer Success", "مدیریت موفقیت مشتری", False),
    ("commercial.manage", "Commercial", "پیشنهاد و نتیجه تجاری", False),
    ("reports.read", "Reports", "مشاهده گزارش‌ها و KPI", False),
    ("audit.read", "Audit", "مشاهده Audit Log", True),
)

ALL_PERMISSION_CODES = {item[0] for item in PERMISSIONS}

SYSTEM_ROLES = {
    "super_admin": ("مدیر کل", ALL_PERMISSION_CODES),
    "admin": (
        "ادمین",
        {
            "users.read",
            "users.manage",
            "roles.read",
            "roles.manage",
            "pilots.read",
            "pilots.create",
            "pilots.manage",
            "preferences.manage",
            "forms.read",
            "forms.print",
            "forms.export_pdf",
            "forms.f01.read",
            "forms.f02.read",
            "forms.f03.read",
            "forms.f04.read",
            "forms.f05.read",
        },
    ),
    "pilot_manager": (
        "مدیر پایلوت",
        {
            "pilots.read",
            "pilots.create",
            "pilots.manage",
            "checklists.manage",
            "gate_approval.approve",
            "gate_approval.reject",
            "reports.read",
            "preferences.manage",
            "forms.read",
            "forms.print",
            "forms.export_pdf",
            "forms.f01.read",
            "forms.f02.read",
            "forms.f03.read",
            "forms.f04.read",
            "forms.f05.read",
        },
    ),
    "sales": (
        "جذب و فروش",
        {
            "pilots.read",
            "pilots.create",
            "stage1.manage",
            "forms.manage",
            "checklists.manage",
            "commercial.manage",
            "preferences.manage",
            "forms.read",
            "forms.print",
            "forms.export_pdf",
            "forms.f01.read",
            "forms.f04.read",
        },
    ),
    "setup": (
        "مسئول راه‌اندازی",
        {
            "pilots.read",
            "forms.manage",
            "dwg.manage",
            "checklists.manage",
            "preferences.manage",
            "forms.read",
            "forms.print",
            "forms.f01.read",
            "forms.f02.read",
        },
    ),
    "operations": (
        "هماهنگ‌کننده عملیات",
        {
            "pilots.read",
            "missions.manage",
            "checklists.manage",
            "gate_approval.approve",
            "preferences.manage",
            "forms.read",
            "forms.print",
            "forms.export_pdf",
            "forms.f02.read",
            "forms.f03.read",
            "forms.f05.read",
        },
    ),
    "capture_expert": (
        "کارشناس برداشت",
        {
            "pilots.read",
            "missions.manage",
            "checklists.manage",
            "incidents.manage",
            "preferences.manage",
            "forms.read",
            "forms.print",
            "forms.f03.read",
            "forms.f05.read",
        },
    ),
    "support": (
        "پشتیبانی و آموزش",
        {
            "pilots.read",
            "checklists.manage",
            "incidents.manage",
            "notifications.manage",
            "customer_success.manage",
            "preferences.manage",
            "forms.read",
            "forms.print",
            "forms.export_pdf",
            "forms.f04.read",
            "forms.f05.read",
        },
    ),
    "customer_success": (
        "موفقیت مشتری",
        {
            "pilots.read",
            "forms.manage",
            "customer_success.manage",
            "gate_approval.approve",
            "preferences.manage",
            "forms.read",
            "forms.print",
            "forms.export_pdf",
            "forms.f04.read",
            "forms.f05.read",
        },
    ),
    "technical": (
        "تیم فنی",
        {
            "pilots.read",
            "incidents.manage",
            "external_status.manage",
            "preferences.manage",
            "forms.read",
            "forms.f05.read",
        },
    ),
    "product_manager": (
        "مدیر محصول",
        {
            "pilots.read",
            "incidents.manage",
            "reports.read",
            "preferences.manage",
            "forms.read",
            "forms.print",
            "forms.export_pdf",
            "forms.f01.read",
            "forms.f02.read",
            "forms.f03.read",
            "forms.f04.read",
            "forms.f05.read",
        },
    ),
}
