"""Canonical BAMBO permission and system-role definitions."""

PERMISSIONS = (
    ("users.read", "Users", "مشاهده کاربران", False),
    ("users.create", "Users", "ایجاد کاربر", True),
    ("users.update", "Users", "ویرایش کاربر", True),
    ("users.disable", "Users", "غیرفعال‌کردن کاربر", True),
    ("users.activate", "Users", "فعال‌کردن کاربر", True),
    ("users.assign_roles", "Users", "تخصیص نقش به کاربر", True),
    ("users.reset_access", "Users", "بازنشانی دسترسی کاربر", True),
    ("users.manage", "Users", "ایجاد و مدیریت کاربران", True),
    ("roles.read", "Roles", "مشاهده نقش‌ها و دسترسی‌ها", False),
    ("roles.create", "Roles", "ایجاد نقش", True),
    ("roles.update", "Roles", "ویرایش نقش", True),
    ("roles.clone", "Roles", "Clone نقش", True),
    ("roles.delete", "Roles", "حذف نقش", True),
    ("roles.manage_permissions", "Roles", "مدیریت Permission نقش", True),
    ("roles.manage", "Roles", "ایجاد نقش و تغییر Permission", True),
    ("pilots.read", "Pilots", "مشاهده پرونده‌های پایلوت", False),
    ("pilots.read_all", "Pilots", "مشاهده همه پایلوت‌ها", True),
    ("pilots.create", "Pilots", "ایجاد پرونده پایلوت", False),
    ("pilots.update", "Pilots", "ویرایش پایلوت", False),
    ("pilots.assign", "Pilots", "تخصیص پایلوت", True),
    ("pilots.archive", "Pilots", "آرشیو پایلوت", True),
    ("pilots.close", "Pilots", "بستن پایلوت", True),
    ("pilots.reopen", "Pilots", "بازگشایی پایلوت", True),
    ("pilots.manage", "Pilots", "ویرایش و مدیریت پرونده پایلوت", True),
    ("projects.read", "Projects", "مشاهده پروژه", False),
    ("projects.create", "Projects", "ایجاد پروژه", False),
    ("projects.update", "Projects", "ویرایش پروژه", False),
    ("projects.manage_floors", "Projects", "مدیریت طبقات", False),
    ("projects.manage_external_references", "Projects", "مدیریت شناسه‌های خارجی", True),
    ("stages.read", "Stages", "مشاهده مراحل", False),
    ("stages.start", "Stages", "شروع مرحله", False),
    ("stages.edit", "Stages", "ویرایش مرحله", False),
    ("stages.save_draft", "Stages", "ذخیره پیش‌نویس مرحله", False),
    ("stages.submit", "Stages", "ارسال مرحله", False),
    ("stages.review", "Stages", "بازبینی مرحله", False),
    ("stages.approve", "Stages", "تأیید مرحله", True),
    ("stages.reject", "Stages", "رد مرحله", True),
    ("stages.request_revision", "Stages", "درخواست اصلاح مرحله", False),
    ("stages.reassign", "Stages", "تغییر مسئول مرحله", True),
    ("stages.unlock", "Stages", "بازکردن مرحله قفل‌شده", True),
    ("stages.view_history", "Stages", "مشاهده تاریخچه مرحله", False),
    ("stages.view_snapshots", "Stages", "مشاهده Snapshot مرحله", False),
    ("stage1.manage", "Stage 1", "مدیریت مرحله اول", False),
    ("gates.read", "Gates", "مشاهده Gateها", False),
    ("gates.evaluate", "Gates", "ارزیابی Gate", False),
    ("gates.approve", "Gates", "تأیید Gate", True),
    ("gates.reject", "Gates", "رد Gate", True),
    ("gates.override", "Gates", "Override Gate", True),
    ("gate_approval.approve", "Gate Approval", "تأیید Gate و مرحله", True),
    ("gate_approval.reject", "Gate Approval", "رد Gate و مرحله", True),
    ("forms.manage", "Forms", "ثبت و ویرایش F01 تا F05", False),
    ("forms.read", "Forms", "مشاهده فرم‌های رسمی پروژه", False),
    ("forms.print", "Forms", "چاپ فرم‌های رسمی پروژه", False),
    ("forms.export_pdf", "Forms", "خروجی PDF فرم‌های رسمی پروژه", False),
    ("forms.f01.read", "Forms", "مشاهده فرم رسمی F01", False),
    ("forms.f02.read", "Forms", "مشاهده فرم رسمی F02", False),
    ("forms.f03.read", "Forms", "مشاهده فرم رسمی F03", False),
    ("forms.f04.read", "Forms", "مشاهده فرم رسمی F04", False),
    ("forms.f05.read", "Forms", "مشاهده فرم رسمی F05", False),
    ("dwg.read", "DWG", "مشاهده DWG", False),
    ("dwg.upload", "DWG", "آپلود DWG", False),
    ("dwg.download", "DWG", "دانلود DWG", False),
    ("dwg.validate", "DWG", "اعتبارسنجی DWG", False),
    ("dwg.create_version", "DWG", "ایجاد نسخه DWG", True),
    ("dwg.reject", "DWG", "رد DWG", True),
    ("dwg.manage", "DWG", "ثبت و نسخه‌بندی DWG", True),
    ("missions.read", "Missions", "مشاهده مأموریت", False),
    ("missions.create", "Missions", "ایجاد مأموریت", False),
    ("missions.update", "Missions", "ویرایش مأموریت", False),
    ("missions.assign", "Missions", "تخصیص مأموریت", False),
    ("missions.reschedule", "Missions", "تغییر زمان مأموریت", False),
    ("missions.cancel", "Missions", "لغو مأموریت", True),
    ("missions.confirm_receipt", "Missions", "تأیید دریافت مأموریت", False),
    ("missions.complete", "Missions", "تکمیل مأموریت", False),
    ("missions.manage", "Missions", "مدیریت مأموریت‌ها", False),
    ("checklists.read", "Checklists", "مشاهده چک‌لیست", False),
    ("checklists.update", "Checklists", "ویرایش چک‌لیست", False),
    ("checklists.submit", "Checklists", "ارسال چک‌لیست", False),
    ("checklists.review", "Checklists", "بازبینی چک‌لیست", False),
    ("checklists.manage", "Checklists", "ثبت چک‌لیست و ارسال مرحله", False),
    ("external_status.manage", "External Platform", "ثبت وضعیت Read-only پلتفرم اصلی", False),
    ("incidents.read", "Incidents", "مشاهده رخداد", False),
    ("incidents.read_all", "Incidents", "مشاهده همه رخدادها", True),
    ("incidents.create", "Incidents", "ایجاد رخداد", False),
    ("incidents.update", "Incidents", "ویرایش رخداد", False),
    ("incidents.assign", "Incidents", "تخصیص رخداد", False),
    ("incidents.contain", "Incidents", "ثبت مهار رخداد", False),
    ("incidents.resolve", "Incidents", "ثبت حل رخداد", False),
    ("incidents.escalate", "Incidents", "Escalate رخداد", True),
    ("incidents.close", "Incidents", "بستن رخداد", False),
    ("incidents.reopen", "Incidents", "بازگشایی رخداد", True),
    ("incidents.approve_closure", "Incidents", "تأیید بسته‌شدن رخداد", True),
    ("incidents.manage", "Incidents", "ثبت و مدیریت رخدادها", False),
    ("customer_success.read", "Customer Success", "مشاهده موفقیت مشتری", False),
    ("customer_success.update", "Customer Success", "ویرایش موفقیت مشتری", False),
    ("customer_success.followup", "Customer Success", "ثبت پیگیری", False),
    ("customer_success.training_record", "Customer Success", "ثبت آموزش", False),
    ("customer_success.feedback", "Customer Success", "ثبت بازخورد", False),
    ("customer_success.manage", "Customer Success", "مدیریت موفقیت مشتری", False),
    ("commercial.read", "Commercial", "مشاهده تجاری", False),
    ("commercial.update", "Commercial", "ویرایش تجاری", False),
    ("commercial.create_proposal", "Commercial", "ایجاد پیشنهاد تجاری", False),
    ("commercial.followup", "Commercial", "پیگیری فروش", False),
    ("commercial.record_outcome", "Commercial", "ثبت نتیجه تجاری", False),
    ("commercial.close_case", "Commercial", "بستن پرونده تجاری", True),
    ("commercial.manage", "Commercial", "پیشنهاد و نتیجه تجاری", False),
    ("reports.read", "Reports", "مشاهده گزارش‌ها و KPI", False),
    ("reports.export", "Reports", "خروجی گزارش", False),
    ("reports.kpi", "Reports", "مشاهده KPI", False),
    ("reports.sla", "Reports", "مشاهده SLA", False),
    ("reports.powerbi", "Reports", "دریافت Embed امن Power BI", True),
    ("dashboard.read", "Dashboard", "مشاهده نمای کلی سامانه", False),
    ("dashboard.read_all", "Dashboard", "مشاهده نمای کلی همه پرونده‌ها", True),
    ("dashboard.export", "Dashboard", "خروجی نمای کلی سامانه", False),
    ("notifications.manage", "Notifications", "ثبت و پیگیری اعلان‌های عملیاتی", False),
    ("notifications.read", "Notifications", "مشاهده اعلان‌های کاربر", False),
    ("notifications.mark_read", "Notifications", "خوانده‌شدن یا حذف اعلان‌های کاربر", False),
    ("notifications.manage_preferences", "Notifications", "مدیریت تنظیمات اعلان", False),
    ("notifications.send_manual", "Notifications", "ارسال دستی اعلان", True),
    ("notifications.delivery_logs.read", "Notifications", "مشاهده لاگ ارسال اعلان‌ها", True),
    ("notifications.templates.manage", "Notifications", "مدیریت Template اعلان‌ها", True),
    ("preferences.manage", "Preferences", "مدیریت تنظیمات کاربر", False),
    ("audit.read", "Audit", "مشاهده Audit Log", True),
    ("audit.export", "Audit", "خروجی Audit Log", True),
    ("system.manage_settings", "System", "مدیریت تنظیمات سیستم", True),
    ("system.manage_otp", "System", "مدیریت OTP", True),
    ("system.manage_notifications", "System", "مدیریت اعلان‌های سیستمی", True),
    ("system.manage_storage", "System", "مدیریت ذخیره‌سازی", True),
    ("system.manage_integrations", "System", "مدیریت Integrationها", True),
)

ALL_PERMISSION_CODES = {item[0] for item in PERMISSIONS}

ADMIN_PERMISSIONS = {
    "users.read",
    "users.create",
    "users.update",
    "users.disable",
    "users.activate",
    "users.assign_roles",
    "users.reset_access",
    "users.manage",
    "roles.read",
    "roles.create",
    "roles.update",
    "roles.clone",
    "roles.delete",
    "roles.manage_permissions",
    "roles.manage",
    "pilots.read",
    "pilots.create",
    "pilots.manage",
    "dashboard.read",
    "dashboard.read_all",
    "dashboard.export",
    "preferences.manage",
    "forms.read",
    "forms.print",
    "forms.export_pdf",
    "notifications.read",
    "notifications.mark_read",
    "notifications.manage_preferences",
    "notifications.send_manual",
    "notifications.delivery_logs.read",
    "notifications.templates.manage",
}

PILOT_MANAGER_PERMISSIONS = {
    "pilots.read",
    "pilots.read_all",
    "pilots.create",
    "pilots.update",
    "pilots.assign",
    "pilots.close",
    "pilots.reopen",
    "pilots.manage",
    "stages.read",
    "stages.review",
    "stages.approve",
    "stages.reject",
    "stages.reassign",
    "stages.view_history",
    "stages.view_snapshots",
    "gates.read",
    "gates.approve",
    "gates.reject",
    "gate_approval.approve",
    "gate_approval.reject",
    "checklists.manage",
    "reports.read",
    "reports.kpi",
    "reports.sla",
    "dashboard.read",
    "dashboard.export",
    "incidents.read",
    "incidents.read_all",
    "incidents.approve_closure",
    "incidents.assign",
    "incidents.close",
    "incidents.escalate",
    "incidents.reopen",
    "preferences.manage",
    "forms.read",
    "forms.print",
    "forms.export_pdf",
}

SALES_PERMISSIONS = {
    "pilots.read",
    "pilots.create",
    "pilots.update",
    "stage1.manage",
    "stages.read",
    "stages.edit",
    "stages.save_draft",
    "stages.submit",
    "forms.manage",
    "forms.read",
    "forms.print",
    "forms.export_pdf",
    "forms.f01.read",
    "forms.f04.read",
    "commercial.read",
    "commercial.update",
    "commercial.create_proposal",
    "commercial.followup",
    "commercial.record_outcome",
    "commercial.close_case",
    "commercial.manage",
    "checklists.manage",
    "preferences.manage",
}

SETUP_PERMISSIONS = {
    "pilots.read",
    "projects.read",
    "projects.create",
    "projects.update",
    "projects.manage_floors",
    "dwg.read",
    "dwg.upload",
    "dwg.download",
    "dwg.validate",
    "dwg.create_version",
    "dwg.reject",
    "dwg.manage",
    "stages.read",
    "stages.edit",
    "stages.save_draft",
    "stages.submit",
    "stages.approve",
    "gates.read",
    "gates.approve",
    "gate_approval.approve",
    "forms.manage",
    "forms.read",
    "forms.print",
    "forms.f01.read",
    "forms.f02.read",
    "checklists.manage",
    "preferences.manage",
}

OPERATIONS_PERMISSIONS = {
    "pilots.read",
    "missions.read",
    "missions.create",
    "missions.update",
    "missions.assign",
    "missions.reschedule",
    "missions.cancel",
    "missions.complete",
    "missions.manage",
    "stages.read",
    "stages.edit",
    "stages.save_draft",
    "stages.submit",
    "stages.approve",
    "stages.reject",
    "gates.read",
    "gates.approve",
    "gates.reject",
    "gate_approval.approve",
    "gate_approval.reject",
    "checklists.read",
    "checklists.review",
    "checklists.manage",
    "incidents.read",
    "incidents.create",
    "incidents.update",
    "incidents.assign",
    "incidents.contain",
    "incidents.resolve",
    "incidents.close",
    "preferences.manage",
    "forms.read",
    "forms.print",
    "forms.export_pdf",
    "forms.f02.read",
    "forms.f03.read",
    "forms.f05.read",
}

FIELD_EXPERT_PERMISSIONS = {
    "pilots.read",
    "missions.read",
    "missions.confirm_receipt",
    "missions.complete",
    "missions.manage",
    "stages.read",
    "stages.edit",
    "stages.save_draft",
    "stages.submit",
    "checklists.read",
    "checklists.update",
    "checklists.submit",
    "checklists.manage",
    "incidents.read",
    "incidents.create",
    "incidents.manage",
    "incidents.update",
    "incidents.contain",
    "forms.read",
    "forms.print",
    "forms.f03.read",
    "forms.f05.read",
    "preferences.manage",
}

SUPPORT_PERMISSIONS = {
    "pilots.read",
    "stages.read",
    "stages.edit",
    "stages.save_draft",
    "stages.submit",
    "checklists.manage",
    "incidents.read",
    "incidents.create",
    "incidents.update",
    "incidents.assign",
    "incidents.contain",
    "incidents.resolve",
    "notifications.manage",
    "customer_success.read",
    "customer_success.training_record",
    "customer_success.manage",
    "forms.read",
    "forms.print",
    "forms.export_pdf",
    "forms.f04.read",
    "forms.f05.read",
    "preferences.manage",
}

CUSTOMER_SUCCESS_PERMISSIONS = {
    "pilots.read",
    "stages.read",
    "stages.edit",
    "stages.save_draft",
    "stages.submit",
    "stages.approve",
    "stages.reject",
    "gates.read",
    "gates.approve",
    "gates.reject",
    "gate_approval.approve",
    "gate_approval.reject",
    "forms.manage",
    "forms.read",
    "forms.print",
    "forms.export_pdf",
    "forms.f04.read",
    "forms.f05.read",
    "customer_success.read",
    "customer_success.update",
    "customer_success.followup",
    "customer_success.training_record",
    "customer_success.feedback",
    "customer_success.manage",
    "preferences.manage",
}

TECHNICAL_PERMISSIONS = {
    "pilots.read",
    "incidents.read",
    "incidents.update",
    "incidents.escalate",
    "incidents.close",
    "incidents.resolve",
    "incidents.manage",
    "external_status.manage",
    "reports.sla",
    "dashboard.read",
    "forms.read",
    "forms.f05.read",
    "preferences.manage",
}

PRODUCT_MANAGER_PERMISSIONS = {
    "pilots.read",
    "incidents.read",
    "incidents.update",
    "incidents.resolve",
    "reports.read",
    "reports.kpi",
    "dashboard.read",
    "dashboard.export",
    "forms.read",
    "forms.print",
    "forms.export_pdf",
    "forms.f01.read",
    "forms.f02.read",
    "forms.f03.read",
    "forms.f04.read",
    "forms.f05.read",
    "preferences.manage",
}

NOTIFICATION_SELF_PERMISSIONS = {
    "notifications.read",
    "notifications.mark_read",
    "notifications.manage_preferences",
}

SYSTEM_ROLES = {
    "super_admin": ("سوپر ادمین", ALL_PERMISSION_CODES),
    "admin": ("ادمین", ADMIN_PERMISSIONS),
    "pilot_manager": ("مدیر پایلوت", PILOT_MANAGER_PERMISSIONS),
    "sales": ("جذب/فروش", SALES_PERMISSIONS),
    "setup": ("مسئول راه‌اندازی", SETUP_PERMISSIONS),
    "operations": ("هماهنگ‌کننده عملیات", OPERATIONS_PERMISSIONS),
    "capture_expert": ("کارشناس برداشت", FIELD_EXPERT_PERMISSIONS),
    "support": ("آموزش/پشتیبانی", SUPPORT_PERMISSIONS),
    "customer_success": ("موفقیت مشتری", CUSTOMER_SUCCESS_PERMISSIONS),
    "technical": ("تیم فنی", TECHNICAL_PERMISSIONS),
    "product_manager": ("مدیر محصول", PRODUCT_MANAGER_PERMISSIONS),
}

for role_name, (_, permission_codes) in SYSTEM_ROLES.items():
    if role_name != "super_admin":
        permission_codes.update(NOTIFICATION_SELF_PERMISSIONS)
        if role_name in {
            "admin",
            "pilot_manager",
            "sales",
            "setup",
            "operations",
            "capture_expert",
            "support",
            "customer_success",
            "technical",
            "product_manager",
        }:
            permission_codes.add("dashboard.read")
