"""Pydantic schemas for the smart building backend."""

from app.schemas.building import BuildingCreate, BuildingRead, BuildingUpdate
from app.schemas.equipment import EquipmentCreate, EquipmentRead, EquipmentUpdate
from app.schemas.sensor import SensorCreate, SensorRead, SensorUpdate
from app.schemas.security import (
    AuditLogRead,
    AuthToken,
    OtpRequestInput,
    OtpRequestResult,
    PermissionRead,
    RoleCreate,
    RolePermissionsUpdate,
    RoleRead,
    RoleSummary,
    UserCreate,
    UserRead,
    UserRolesUpdate,
    UserStatusUpdate,
)
from app.schemas.product import (
    DwgVersionRead,
    FloorCreate,
    FloorRead,
    FormF01Read,
    FormF01Update,
    FormF02Read,
    FormF02Update,
    OwnerCreate,
    OwnerRead,
    ProjectCreate,
    ProjectRead,
)
from app.schemas.operations import (
    FormF03Read,
    FormF03Update,
    MissionCreate,
    MissionFloorRead,
    MissionFloorUpdate,
    MissionRead,
    MissionReschedule,
    NotificationRead,
)
from app.schemas.workflow import (
    GateRead,
    PilotCreate,
    PilotDetail,
    PilotRead,
    SnapshotRead,
    StageActionResult,
    StageDecision,
    StageRead,
    StageReject,
    StageSubmit,
    SubmissionRead,
)

__all__ = [
    "BuildingCreate",
    "BuildingRead",
    "BuildingUpdate",
    "EquipmentCreate",
    "EquipmentRead",
    "EquipmentUpdate",
    "SensorCreate",
    "SensorRead",
    "SensorUpdate",
    "AuditLogRead",
    "AuthToken",
    "OtpRequestInput",
    "OtpRequestResult",
    "PermissionRead",
    "DwgVersionRead",
    "FloorCreate",
    "FloorRead",
    "FormF01Read",
    "FormF01Update",
    "FormF02Read",
    "FormF02Update",
    "FormF03Read",
    "FormF03Update",
    "OwnerCreate",
    "OwnerRead",
    "MissionCreate",
    "MissionFloorRead",
    "MissionFloorUpdate",
    "MissionRead",
    "MissionReschedule",
    "NotificationRead",
    "ProjectCreate",
    "ProjectRead",
    "RoleCreate",
    "RolePermissionsUpdate",
    "RoleRead",
    "RoleSummary",
    "UserCreate",
    "UserRead",
    "UserRolesUpdate",
    "UserStatusUpdate",
    "GateRead",
    "PilotCreate",
    "PilotDetail",
    "PilotRead",
    "SnapshotRead",
    "StageActionResult",
    "StageDecision",
    "StageRead",
    "StageReject",
    "StageSubmit",
    "SubmissionRead",
]
