"""Pydantic schemas for the smart building backend."""

from app.schemas.building import BuildingCreate, BuildingRead, BuildingUpdate
from app.schemas.equipment import EquipmentCreate, EquipmentRead, EquipmentUpdate
from app.schemas.sensor import SensorCreate, SensorRead, SensorUpdate
from app.schemas.security import (
    AuditLogRead,
    AuthToken,
    OtpRequestInput,
    OtpRequestResult,
    PermissionRead,
    RoleCreate,
    RolePermissionsUpdate,
    RoleRead,
    RoleSummary,
    UserCreate,
    UserRead,
    UserRolesUpdate,
    UserStatusUpdate,
)
from app.schemas.workflow import (
    GateRead,
    PilotCreate,
    PilotDetail,
    PilotRead,
    SnapshotRead,
    StageActionResult,
    StageDecision,
    StageRead,
    StageReject,
    StageSubmit,
    SubmissionRead,
)

__all__ = [
    "BuildingCreate",
    "BuildingRead",
    "BuildingUpdate",
    "EquipmentCreate",
    "EquipmentRead",
    "EquipmentUpdate",
    "SensorCreate",
    "SensorRead",
    "SensorUpdate",
    "AuditLogRead",
    "AuthToken",
    "OtpRequestInput",
    "OtpRequestResult",
    "PermissionRead",
    "RoleCreate",
    "RolePermissionsUpdate",
    "RoleRead",
    "RoleSummary",
    "UserCreate",
    "UserRead",
    "UserRolesUpdate",
    "UserStatusUpdate",
    "GateRead",
    "PilotCreate",
    "PilotDetail",
    "PilotRead",
    "SnapshotRead",
    "StageActionResult",
    "StageDecision",
    "StageRead",
    "StageReject",
    "StageSubmit",
    "SubmissionRead",
]
